### ISSUE TITLE
ZigBee Light Link

### ISSUE THREAD

**Issue by wldevries** [Seeed-Studio/Mesh_Bee#10]
Any chance any part of ZigBee Light Link will be implemented in the firmware? The chip used on the Mesh Bee seems to be supported.

http://www.nxp.com/products/interface-and-connectivity/wireless-connectivity/2.4-ghz-wireless-solutions/zigbee/zigbee-light-link:ZIGBEE-LIGHT-LINK

**Comment by KillingJacky** [comment]
Sorry, we have no plan implementing Zigbee LL profile.

**Comment by peeveeone** [comment]
Sorry for the shameless plug. I managed to create Light Link firmware which runs on the Mesh Bee, at the moment it is limited to a color light or a monochrome light. More details: http://peeveeone.com/?p=187

**Comment by wldevries** [comment]
This is awesome, was just about to order but now I'll try this out.

Have you tested controlling two devices with the same cloned firmware? I'm wondering whether there is some identifier buried within the firmware that might cause problems.

**Comment by peeveeone** [comment]
The firmware versions for download are no clones, they are a custom implementation of the stated lights. This means you can connect as many instances of them as you please, they are all unique to the network. I can highly recommend using the Mesh Bee's to to do so!
