### ISSUE TITLE
AT commands 

### ISSUE THREAD

**Issue by mostafa-elboss** [Seeed-Studio/Mesh_Bee#11]
is there any way to SEND remote AT command from MCU mode, 
i need to execute some AT commands while code executing ?

**Comment by KillingJacky** [comment]
Yes, the thinking is, use the rpc framework to send rpc call to the remote side, and then do things (like operating IOs or I2C bus) in the proc at remote side.

**Comment by mostafa-elboss** [comment]
sorry but what i mean is can i execute local at command from MCU mode. like create network and join network .
 

    On Monday, April 11, 2016 4:21 AM, Jack Shao <notifications@github.com> wrote:
 

 Yes, the thinking is, use the rpc framework to send rpc call to the remote side, and then do things (like operating IOs or I2C bus) in the proc at remote side.—

**Comment by KillingJacky** [comment]
Afraid not. These operations can be executed no need of at commands, you can call the zigbee sdk directly.
