### ISSUE TITLE
API mode 1004

### ISSUE THREAD

**Issue by mostafa-elboss** [Seeed-Studio/Mesh_Bee#9]
iam working now on Firmware 1004, and notice that API mode does not send data 
kindly check this

**Comment by KillingJacky** [comment]
Hi,
Could you show us how you construct the API frame?

**Comment by mostafa-elboss** [comment]
when i was working on v1003 
i tried the example that was written on cookdoor PDF 
char msg[]={0x7e,0x19,0x02,0xec,0x00,0x06,'s','e','e','e','d',0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xf8};
then developed my routine 
sum=0;
for(i=0;i<25;i++) sum+=payload[i];  // payload represent API Specific frame  , sum is CRC 
uart1_write(0x7e);
uart1_write(0x19);
uart1_write(0x02);
for(i=0;i<25;i++)
uart1_write(payload[i]);  
uart1_write(sum);    
 delay_ms(50);
 }
both worked for V1003 

after i switched to V1004, developed routine didn't work , so i tried again the one in cookbook it did not work also .

**Comment by KillingJacky** [comment]
Thanks for reporting, we'll look into it. Will feedback you ASAP.

**Comment by mostafa-elboss** [comment]
thanks for your response 
another thing i noticed in cookbook in API frame example page 20 is written at 
serial.write(x00)   //address low 
serial.write(x00)   //address high 
then crc 
i think comment is wrong , in this situation low=high so wonot be a problem 
but if required address xABCD 
we must send high first xAB 
then low xCD

**Comment by KillingJacky** [comment]
Hi,

Thanks for reminding. Yes, the comment is wrong. And we figured out that the difference against v1003 is that the data structure has changed.

Before we revise the cookbook, you can refer to this struct to construct your API frame:

struct
{
    uint8 frameId;
    uint8 option;             //Indicate broadcast or unicast,need ACK or not.
    uint16 unicastAddr;       //unicast address
    uint64 unicastAddr64;
    uint8 dataLen;            //data length in data array
    uint8 data[32]; //data array
}__attribute__ ((packed)) tsTxDataPacket;

This should replace the description of 
![image](https://cloud.githubusercontent.com/assets/5130185/12476331/99b32c94-c063-11e5-9c37-d79baf27d5d8.png) in section 5.1.1 of cookbook.

unicastAddr64 will be used if unicastAddr == 0xfffe, else unicastAddr will be used as the dest address.

dataLen can be flexible, with max length 32.

crc should be the summary of all the bytes in this struct.

We will update the cookbook ASAP, and will notify you here when new cookbook uploaded.

**Comment by mostafa-elboss** [comment]
Great , it works correctly 
Thanks

**Comment by KillingJacky** [comment]
Hi,
The docs are updated:
User Manual: http://www.seeedstudio.com/wiki/File:MeshBee_User_Manual_v0.3.pdf
Cook Book: http://www.seeedstudio.com/wiki/File:MeshBee_Cook_Book.pdf

**Comment by mostafa-elboss** [comment]
Thanks a LOT 
i have another question . can i access EEPROM memory

**Comment by KillingJacky** [comment]
Yes, but with support os JenOS APIs, a little bit complicated to explain here. Suggest you read chapter 8 in JN-UG-3075-JenOS.pdf
![image](https://cloud.githubusercontent.com/assets/5130185/12510199/295b0580-c143-11e5-9cc6-b9af84fd3d48.png)

**Comment by mostafa-elboss** [comment]
thanks for your support

**Comment by KillingJacky** [comment]
you're welcome.
